# Generated by Django 4.0.5 on 2022-06-06 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categories_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('categories_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('content', models.TextField(default='')),
                ('time', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False)),
                ('image', models.TextField(default='')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categories')),
            ],
        ),
    ]
