# Generated by Django 4.0.5 on 2022-06-06 07:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
