# Generated by Django 4.0.5 on 2022-06-07 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_posts_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_user', models.CharField(default='', max_length=255)),
                ('comment_email', models.CharField(default='', max_length=255, null=True)),
                ('comment_content', models.TextField(default='')),
                ('posts_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.posts')),
            ],
        ),
    ]
